imdb_dbt:

  target: local
  outputs:
    local:
      type: sqlite

      # sqlite locks the whole db on writes so anything > 1 won't help
      threads: 1

      # value is arbitrary
      database: "database"

      # value of 'schema' must be defined in schema_paths below. in most cases,
      # this should be 'main'
      schema: 'main'

      # connect schemas to paths: at least one of these must be 'main'
      schemas_and_paths:
        main: '../staging.db'
        main_etl: '../etl.db'

      # directory where all *.db files are attached as schema, using base filename
      # as schema name, and where new schema are created. this can overlap with the dirs of
      # files in schemas_and_paths as long as there's no conflicts.
      schema_directory: '../'

      # optional: list of file paths of SQLite extensions to load.
      # crypto.so is needed for snapshots to work; see README
      extensions:
        - "sqlite/crypto.dll"